const predefinedQuestions = [
  {"title":"Two Sum","platform":"LeetCode","difficulty":"Easy","tags":["Array","HashMap"],"url":"https://leetcode.com/problems/two-sum/","isPredefined":true},
  {"title":"Best Time to Buy and Sell Stock","platform":"LeetCode","difficulty":"Easy","tags":["Array"],"url":"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/","isPredefined":true},
  {"title":"Contains Duplicate","platform":"LeetCode","difficulty":"Easy","tags":["Array","HashSet"],"url":"https://leetcode.com/problems/contains-duplicate/","isPredefined":true},
  {"title":"Product of Array Except Self","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/product-of-array-except-self/","isPredefined":true},
  {"title":"Maximum Subarray","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/maximum-subarray/","isPredefined":true},
  {"title":"Maximum Product Subarray","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/maximum-product-subarray/","isPredefined":true},
  {"title":"Find Minimum in Rotated Sorted Array","platform":"LeetCode","difficulty":"Medium","tags":["Binary Search"],"url":"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/","isPredefined":true},
  {"title":"Search in Rotated Sorted Array","platform":"LeetCode","difficulty":"Medium","tags":["Binary Search"],"url":"https://leetcode.com/problems/search-in-rotated-sorted-array/","isPredefined":true},
  {"title":"Climbing Stairs","platform":"LeetCode","difficulty":"Easy","tags":["DP"],"url":"https://leetcode.com/problems/climbing-stairs/","isPredefined":true},
  {"title":"House Robber","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/house-robber/","isPredefined":true},
  {"title":"House Robber II","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/house-robber-ii/","isPredefined":true},
  {"title":"Coin Change","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/coin-change/","isPredefined":true},
  {"title":"Longest Increasing Subsequence","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/longest-increasing-subsequence/","isPredefined":true},
  {"title":"Word Break","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/word-break/","isPredefined":true},
  {"title":"Combination Sum","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/combination-sum/","isPredefined":true},
  {"title":"Combination Sum II","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/combination-sum-ii/","isPredefined":true},
  {"title":"Valid Parentheses","platform":"LeetCode","difficulty":"Easy","tags":["Stack"],"url":"https://leetcode.com/problems/valid-parentheses/","isPredefined":true},
  {"title":"Min Stack","platform":"LeetCode","difficulty":"Medium","tags":["Stack"],"url":"https://leetcode.com/problems/min-stack/","isPredefined":true},
  {"title":"Evaluate Reverse Polish Notation","platform":"LeetCode","difficulty":"Medium","tags":["Stack"],"url":"https://leetcode.com/problems/evaluate-reverse-polish-notation/","isPredefined":true},
  {"title":"Daily Temperatures","platform":"LeetCode","difficulty":"Medium","tags":["Stack"],"url":"https://leetcode.com/problems/daily-temperatures/","isPredefined":true},
  {"title":"Valid Anagram","platform":"LeetCode","difficulty":"Easy","tags":["String"],"url":"https://leetcode.com/problems/valid-anagram/","isPredefined":true},
  {"title":"Group Anagrams","platform":"LeetCode","difficulty":"Medium","tags":["String","HashMap"],"url":"https://leetcode.com/problems/group-anagrams/","isPredefined":true},
  {"title":"Longest Substring Without Repeating Characters","platform":"LeetCode","difficulty":"Medium","tags":["Sliding Window"],"url":"https://leetcode.com/problems/longest-substring-without-repeating-characters/","isPredefined":true},
  {"title":"Longest Repeating Character Replacement","platform":"LeetCode","difficulty":"Medium","tags":["Sliding Window"],"url":"https://leetcode.com/problems/longest-repeating-character-replacement/","isPredefined":true},
  {"title":"Minimum Window Substring","platform":"LeetCode","difficulty":"Hard","tags":["Sliding Window"],"url":"https://leetcode.com/problems/minimum-window-substring/","isPredefined":true},
  {"title":"Merge Two Sorted Lists","platform":"LeetCode","difficulty":"Easy","tags":["Linked List"],"url":"https://leetcode.com/problems/merge-two-sorted-lists/","isPredefined":true},
  {"title":"Reverse Linked List","platform":"LeetCode","difficulty":"Easy","tags":["Linked List"],"url":"https://leetcode.com/problems/reverse-linked-list/","isPredefined":true},
  {"title":"Linked List Cycle","platform":"LeetCode","difficulty":"Easy","tags":["Linked List"],"url":"https://leetcode.com/problems/linked-list-cycle/","isPredefined":true},
  {"title":"Reorder List","platform":"LeetCode","difficulty":"Medium","tags":["Linked List"],"url":"https://leetcode.com/problems/reorder-list/","isPredefined":true},
  {"title":"Invert Binary Tree","platform":"LeetCode","difficulty":"Easy","tags":["Tree"],"url":"https://leetcode.com/problems/invert-binary-tree/","isPredefined":true},
  {"title":"Maximum Depth of Binary Tree","platform":"LeetCode","difficulty":"Easy","tags":["Tree"],"url":"https://leetcode.com/problems/maximum-depth-of-binary-tree/","isPredefined":true},
  {"title":"Same Tree","platform":"LeetCode","difficulty":"Easy","tags":["Tree"],"url":"https://leetcode.com/problems/same-tree/","isPredefined":true},
  {"title":"Binary Tree Level Order Traversal","platform":"LeetCode","difficulty":"Medium","tags":["Tree"],"url":"https://leetcode.com/problems/binary-tree-level-order-traversal/","isPredefined":true},
  {"title":"Number of Islands","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/number-of-islands/","isPredefined":true},
  {"title":"Clone Graph","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/clone-graph/","isPredefined":true},
  {"title":"Course Schedule","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/course-schedule/","isPredefined":true},
  {"title":"Kth Largest Element in an Array","platform":"LeetCode","difficulty":"Medium","tags":["Heap"],"url":"https://leetcode.com/problems/kth-largest-element-in-an-array/","isPredefined":true},
  {"title":"Top K Frequent Elements","platform":"LeetCode","difficulty":"Medium","tags":["Heap"],"url":"https://leetcode.com/problems/top-k-frequent-elements/","isPredefined":true},
  {"title":"Binary Search","platform":"LeetCode","difficulty":"Easy","tags":["Binary Search"],"url":"https://leetcode.com/problems/binary-search/","isPredefined":true},
  {"title":"Search a 2D Matrix","platform":"LeetCode","difficulty":"Medium","tags":["Binary Search"],"url":"https://leetcode.com/problems/search-a-2d-matrix/","isPredefined":true},
  {"title":"Trapping Rain Water","platform":"LeetCode","difficulty":"Hard","tags":["Two Pointer"],"url":"https://leetcode.com/problems/trapping-rain-water/","isPredefined":true},
  {"title":"Container With Most Water","platform":"LeetCode","difficulty":"Medium","tags":["Two Pointer"],"url":"https://leetcode.com/problems/container-with-most-water/","isPredefined":true},
  {"title":"3Sum","platform":"LeetCode","difficulty":"Medium","tags":["Array","Two Pointer"],"url":"https://leetcode.com/problems/3sum/","isPredefined":true},
  {"title":"4Sum","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/4sum/","isPredefined":true},
  {"title":"Sort Colors","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/sort-colors/","isPredefined":true},
  {"title":"Next Permutation","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/next-permutation/","isPredefined":true},
  {"title":"Set Matrix Zeroes","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/set-matrix-zeroes/","isPredefined":true},
  {"title":"Spiral Matrix","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/spiral-matrix/","isPredefined":true},
  {"title":"Rotate Image","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/rotate-image/","isPredefined":true},
  {"title":"Merge Intervals","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/merge-intervals/","isPredefined":true},
  {"title":"Insert Interval","platform":"LeetCode","difficulty":"Medium","tags":["Array"],"url":"https://leetcode.com/problems/insert-interval/","isPredefined":true},
  {"title":"Non-overlapping Intervals","platform":"LeetCode","difficulty":"Medium","tags":["Greedy"],"url":"https://leetcode.com/problems/non-overlapping-intervals/","isPredefined":true},
  {"title":"Jump Game","platform":"LeetCode","difficulty":"Medium","tags":["Greedy"],"url":"https://leetcode.com/problems/jump-game/","isPredefined":true},
  {"title":"Jump Game II","platform":"LeetCode","difficulty":"Medium","tags":["Greedy"],"url":"https://leetcode.com/problems/jump-game-ii/","isPredefined":true},
  {"title":"Gas Station","platform":"LeetCode","difficulty":"Medium","tags":["Greedy"],"url":"https://leetcode.com/problems/gas-station/","isPredefined":true},
  {"title":"Candy","platform":"LeetCode","difficulty":"Hard","tags":["Greedy"],"url":"https://leetcode.com/problems/candy/","isPredefined":true},
  {"title":"Task Scheduler","platform":"LeetCode","difficulty":"Medium","tags":["Greedy"],"url":"https://leetcode.com/problems/task-scheduler/","isPredefined":true},
  {"title":"Subsets","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/subsets/","isPredefined":true},
  {"title":"Subsets II","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/subsets-ii/","isPredefined":true},
  {"title":"Permutations","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/permutations/","isPredefined":true},
  {"title":"Permutations II","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/permutations-ii/","isPredefined":true},
  {"title":"N-Queens","platform":"LeetCode","difficulty":"Hard","tags":["Backtracking"],"url":"https://leetcode.com/problems/n-queens/","isPredefined":true},
  {"title":"Word Search","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/word-search/","isPredefined":true},
  {"title":"Palindrome Partitioning","platform":"LeetCode","difficulty":"Medium","tags":["Backtracking"],"url":"https://leetcode.com/problems/palindrome-partitioning/","isPredefined":true},
  {"title":"Unique Paths","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/unique-paths/","isPredefined":true},
  {"title":"Unique Paths II","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/unique-paths-ii/","isPredefined":true},
  {"title":"Minimum Path Sum","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/minimum-path-sum/","isPredefined":true},
  {"title":"Edit Distance","platform":"LeetCode","difficulty":"Hard","tags":["DP"],"url":"https://leetcode.com/problems/edit-distance/","isPredefined":true},
  {"title":"Decode Ways","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/decode-ways/","isPredefined":true},
  {"title":"Partition Equal Subset Sum","platform":"LeetCode","difficulty":"Medium","tags":["DP"],"url":"https://leetcode.com/problems/partition-equal-subset-sum/","isPredefined":true},
  {"title":"Longest Palindromic Substring","platform":"LeetCode","difficulty":"Medium","tags":["String"],"url":"https://leetcode.com/problems/longest-palindromic-substring/","isPredefined":true},
  {"title":"Palindromic Substrings","platform":"LeetCode","difficulty":"Medium","tags":["String"],"url":"https://leetcode.com/problems/palindromic-substrings/","isPredefined":true},
  {"title":"Add Two Numbers","platform":"LeetCode","difficulty":"Medium","tags":["Linked List"],"url":"https://leetcode.com/problems/add-two-numbers/","isPredefined":true},
  {"title":"Remove Nth Node From End","platform":"LeetCode","difficulty":"Medium","tags":["Linked List"],"url":"https://leetcode.com/problems/remove-nth-node-from-end-of-list/","isPredefined":true},
  {"title":"Lowest Common Ancestor of BST","platform":"LeetCode","difficulty":"Easy","tags":["Tree"],"url":"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/","isPredefined":true},
  {"title":"Validate Binary Search Tree","platform":"LeetCode","difficulty":"Medium","tags":["Tree"],"url":"https://leetcode.com/problems/validate-binary-search-tree/","isPredefined":true},
  {"title":"Kth Smallest Element in BST","platform":"LeetCode","difficulty":"Medium","tags":["Tree"],"url":"https://leetcode.com/problems/kth-smallest-element-in-a-bst/","isPredefined":true},
  {"title":"Serialize and Deserialize Binary Tree","platform":"LeetCode","difficulty":"Hard","tags":["Tree"],"url":"https://leetcode.com/problems/serialize-and-deserialize-binary-tree/","isPredefined":true},
  {"title":"Pacific Atlantic Water Flow","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/pacific-atlantic-water-flow/","isPredefined":true},
  {"title":"Rotting Oranges","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/rotting-oranges/","isPredefined":true},
  {"title":"Network Delay Time","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/network-delay-time/","isPredefined":true},
  {"title":"Cheapest Flights Within K Stops","platform":"LeetCode","difficulty":"Medium","tags":["Graph"],"url":"https://leetcode.com/problems/cheapest-flights-within-k-stops/","isPredefined":true},
  {"title":"Implement Trie","platform":"LeetCode","difficulty":"Medium","tags":["Trie"],"url":"https://leetcode.com/problems/implement-trie-prefix-tree/","isPredefined":true},
  {"title":"Design Add and Search Words","platform":"LeetCode","difficulty":"Medium","tags":["Trie"],"url":"https://leetcode.com/problems/design-add-and-search-words-data-structure/","isPredefined":true},
  {"title":"Find Median from Data Stream","platform":"LeetCode","difficulty":"Hard","tags":["Heap"],"url":"https://leetcode.com/problems/find-median-from-data-stream/","isPredefined":true},
  {"title":"Sliding Window Maximum","platform":"LeetCode","difficulty":"Hard","tags":["Heap"],"url":"https://leetcode.com/problems/sliding-window-maximum/","isPredefined":true},
  {"title":"Single Number","platform":"LeetCode","difficulty":"Easy","tags":["Bit Manipulation"],"url":"https://leetcode.com/problems/single-number/","isPredefined":true},
  {"title":"Number of 1 Bits","platform":"LeetCode","difficulty":"Easy","tags":["Bit Manipulation"],"url":"https://leetcode.com/problems/number-of-1-bits/","isPredefined":true},
  {"title":"Counting Bits","platform":"LeetCode","difficulty":"Easy","tags":["Bit Manipulation"],"url":"https://leetcode.com/problems/counting-bits/","isPredefined":true},
  {"title":"Reverse Bits","platform":"LeetCode","difficulty":"Easy","tags":["Bit Manipulation"],"url":"https://leetcode.com/problems/reverse-bits/","isPredefined":true},
  {"title":"Pow(x, n)","platform":"LeetCode","difficulty":"Medium","tags":["Math"],"url":"https://leetcode.com/problems/powx-n/","isPredefined":true},
  {"title":"Sqrt(x)","platform":"LeetCode","difficulty":"Easy","tags":["Math"],"url":"https://leetcode.com/problems/sqrtx/","isPredefined":true},
  {"title":"Median of Two Sorted Arrays","platform":"LeetCode","difficulty":"Hard","tags":["Binary Search"],"url":"https://leetcode.com/problems/median-of-two-sorted-arrays/","isPredefined":true}
];

module.exports = predefinedQuestions;
